# Generated by Django 2.1.2 on 2019-03-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulanguages',
            name='language_name',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
