# Generated by Django 2.1.2 on 2019-03-11 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190308_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(max_length=122)),
                ('telephone_number_text', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('mail_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Donor_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=122)),
                ('donor_is_who', models.CharField(max_length=122)),
                ('donor_description', models.TextField()),
                ('donor_image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=44)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('upcoming', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=265)),
                ('total_donation_title', models.CharField(max_length=122)),
                ('total_donation_text', models.TextField()),
                ('total_donation_amount', models.CharField(max_length=122)),
                ('total_volunteers_title', models.CharField(max_length=122)),
                ('total_volunteers_text', models.TextField()),
                ('total_volunteers_amount', models.CharField(max_length=15)),
                ('future_plans_title', models.CharField(max_length=122)),
                ('future_plans_text', models.TextField()),
                ('future_plans_amount', models.CharField(max_length=22)),
                ('total_projects_title', models.CharField(max_length=33)),
                ('total_projects_amount', models.CharField(max_length=22)),
                ('image_welcome_acc', models.ImageField(blank=True, upload_to='')),
                ('our_key_features_title', models.CharField(max_length=122)),
                ('our_key_features_text', models.TextField()),
                ('sponsorship_title', models.CharField(max_length=44)),
                ('sponsorship_text', models.TextField()),
                ('donate_amount_title', models.CharField(max_length=44)),
                ('donate_amount_text', models.TextField()),
                ('become_volunteer_title', models.CharField(max_length=44)),
                ('become_volunteer_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=122)),
                ('message_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=122)),
                ('birth', models.DateTimeField()),
                ('is_doing', models.CharField(max_length=122)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='languages',
            name='language_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Languages'),
        ),
        migrations.AddField(
            model_name='home',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Languages'),
        ),
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Languages'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Languages'),
        ),
    ]
