# Generated by Django 2.1.2 on 2019-03-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_donor_review_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_need_help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=122)),
                ('animal_image1', models.ImageField(blank=True, upload_to='')),
                ('animal_image2', models.ImageField(blank=True, upload_to='')),
                ('animal_image3', models.ImageField(blank=True, upload_to='')),
                ('animal_image4', models.ImageField(blank=True, upload_to='')),
                ('animal_image5', models.ImageField(blank=True, upload_to='')),
                ('animal_image6', models.ImageField(blank=True, upload_to='')),
                ('animal_image7', models.ImageField(blank=True, upload_to='')),
                ('animal_image8', models.ImageField(blank=True, upload_to='')),
                ('animal_image9', models.ImageField(blank=True, upload_to='')),
                ('animal_image10', models.ImageField(blank=True, upload_to='')),
                ('animal_image11', models.ImageField(blank=True, upload_to='')),
                ('animal_image12', models.ImageField(blank=True, upload_to='')),
                ('animal_image13', models.ImageField(blank=True, upload_to='')),
                ('animal_need_amount', models.IntegerField()),
                ('animal_is_donated', models.IntegerField(default=0)),
            ],
        ),
    ]
