# Generated by Django 2.1.2 on 2019-03-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190312_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donor_name', models.CharField(max_length=122)),
                ('Donor_surname', models.CharField(max_length=122)),
                ('Donor_gives', models.IntegerField()),
                ('Donation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='text',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='animal_image1',
            new_name='event_image1',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='animal_image10',
            new_name='event_image10',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='animal_image11',
            new_name='event_image11',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='animal_image12',
            new_name='event_image12',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='animal_image13',
            new_name='event_image13',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='animal_image2',
            new_name='event_image2',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='animal_image3',
            new_name='event_image3',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='animal_image4',
            new_name='event_image4',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='animal_image5',
            new_name='event_image5',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='animal_image6',
            new_name='event_image6',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='animal_image7',
            new_name='event_image7',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='animal_image8',
            new_name='event_image8',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='animal_image9',
            new_name='event_image9',
        ),
        migrations.AddField(
            model_name='animal_need_help',
            name='donation_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal_need_help',
            name='donor',
            field=models.ManyToManyField(to='home.Donor_Details'),
        ),
    ]
