# Generated by Django 2.1.2 on 2019-03-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190315_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal_need_help',
            name='donation_amount',
        ),
    ]
