# Generated by Django 2.1.2 on 2019-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_animal_need_help_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_little_detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
