# Generated by Django 2.1.2 on 2019-04-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190404_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
