# Generated by Django 2.1.2 on 2019-06-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20190615_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='testimonial_text',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='testimonial_title',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
