# Generated by Django 2.1.2 on 2019-06-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_languages_language_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='language',
        ),
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.ManyToManyField(to='home.Languages'),
        ),
    ]
