# Generated by Django 2.1.2 on 2019-06-16 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20190616_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='details',
            new_name='details_in_az',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_little_detail',
            new_name='details_in_eng',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_adress',
            new_name='event_address',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='title_in_az',
        ),
        migrations.AddField(
            model_name='event',
            name='event_little_detail_in_az',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_little_detail_in_eng',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title_in_eng',
            field=models.CharField(default=1, max_length=44),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='event',
            name='language',
        ),
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Languages'),
            preserve_default=False,
        ),
    ]
