# Generated by Django 2.1.2 on 2019-06-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20190616_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='language',
        ),
        migrations.AddField(
            model_name='contacts',
            name='our_address',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='our_address_detailed',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
