# Generated by Django 2.1.2 on 2019-06-17 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20190618_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='report',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Report'),
        ),
    ]
