# Generated by Django 2.1.2 on 2019-06-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20190618_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='future_plans_text',
            field=models.TextField(),
        ),
    ]
