# Generated by Django 2.1.2 on 2019-06-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_menu_rescued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_main',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image1',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image10',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image11',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image12',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image13',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image14',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image15',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image16',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image17',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image18',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image19',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image2',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image20',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image21',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image22',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image23',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image24',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image25',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image26',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image27',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image28',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image29',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image3',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image30',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image31',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image32',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image33',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image34',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image35',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image36',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image37',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image38',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image39',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image4',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image40',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image5',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image6',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image7',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image8',
            field=models.CharField(blank=True, max_length=720),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image9',
            field=models.CharField(blank=True, max_length=720),
        ),
    ]
