# Generated by Django 2.1.2 on 2019-06-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20190622_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_main',
            field=models.CharField(blank=True, max_length=720),
        ),
    ]
