# Generated by Django 2.1.2 on 2019-09-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_event_image_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_iframe',
            field=models.CharField(default=1, max_length=720),
            preserve_default=False,
        ),
    ]
