# Generated by Django 2.1.2 on 2019-09-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_event_event_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_iframe',
            field=models.CharField(blank=True, max_length=720),
        ),
    ]
