# Generated by Django 2.1.2 on 2019-03-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190311_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor_review',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Languages'),
            preserve_default=False,
        ),
    ]
