# Generated by Django 2.1.2 on 2019-04-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_menu_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
    ]
