# Generated by Django 2.1.2 on 2019-04-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
