# Generated by Django 2.1.2 on 2019-06-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_home_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
