# Generated by Django 2.1.2 on 2019-06-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='future_plans_amount',
        ),
        migrations.AddField(
            model_name='home',
            name='about_us_text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='about_us_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='future_plans_text',
            field=models.CharField(max_length=22),
        ),
    ]
