# Generated by Django 2.1.2 on 2019-06-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20190615_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='future_plans_amount',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
