# Generated by Django 2.1.2 on 2019-06-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20190615_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='future_plans_text',
            field=models.TextField(max_length=60),
        ),
    ]
