# Generated by Django 2.1.2 on 2019-06-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20190615_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='language_short_name',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
