# Generated by Django 2.1.2 on 2019-06-17 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20190617_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=44)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Report'),
            preserve_default=False,
        ),
    ]
