# Generated by Django 2.1.2 on 2019-06-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20190620_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image14',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image15',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image16',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image17',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image18',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image19',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image20',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image21',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image22',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image23',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image24',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image25',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image26',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image27',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image28',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image29',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image30',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image31',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image32',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image33',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image34',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image35',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image36',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image37',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image38',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image39',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image40',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
