# Generated by Django 2.1.2 on 2019-06-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20190622_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='rescued',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
